services:
  eureka-server:
    build:
      context: ./Eureka_Service
    image: ${EUREKA_SERVICE_IMAGE}
    container_name: ${EUREKA_SERVICE_CONTAINER}
    ports:
      - "${EUREKA_SERVICE_PORT}:${EUREKA_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${EUREKA_SERVICE_PORT}
    restart: always
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "${EUREKA_HEALTHCHECK_URL}"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5

  gateway-server:
    build:
      context: ./Gateway_Service
    image: ${EUREKA_GATEWAY_IMAGE}
    container_name: ${EUREKA_GATEWAY_CONTAINER}
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    environment:
      SERVER_PORT: ${GATEWAY_SERVICE_PORT}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    restart: always
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge