package com.picksave.auth_service.Responses;

public enum ErrorCode {
    PASSWORD_INVALID_FORMAT,
    EMAIL_ALREADY_REGISTERED,
    USERNAME_ALREADY_REGISTERED,
    USER_NOT_FOUND,
    EMAIL_NOT_VERIFIED,
    INVALID_EMAIL_OR_PASSWORD,
    VERIFICATION_CODE_EXPIRED,
    INVALID_VERIFICATION_CODE,
    ACCOUNT_ALREADY_VERIFIED,
}
