#!/bin/bash

set -e

# Create auth_db and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE $AUTH_DB;
  CREATE USER $AUTH_DB_USER WITH ENCRYPTED PASSWORD '$AUTH_DB_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB TO $AUTH_DB_USER;
EOSQL
